services:
  db:
    image: postgres:16-alpine
    container_name: quizzy-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: quizzy_dev
      POSTGRES_USER: quizzy_user
      POSTGRES_PASSWORD: quizzy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quizzy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizzy_user -d quizzy_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    container_name: quizzy-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://quizzy_user:quizzy_password@db:5432/quizzy_dev
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - /app/node_modules
      - /app/apps/backend/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quizzy-network

  # Frontend (Next.js)
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    container_name: quizzy-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - /app/node_modules
      - /app/apps/frontend/node_modules
    depends_on:
      - backend
    networks:
      - quizzy-network

volumes:
  postgres_data:

networks:
  quizzy-network:
    driver: bridge
