
services:
  postgres:
    image: postgres:16-alpine
    container_name: quizzy-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quizz
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .                    
      dockerfile: apps/backend/Dockerfile
    container_name: quizzy-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app                        
    depends_on:
      - postgres

  frontend:
    build:
      context: .                     
      dockerfile: apps/frontend/Dockerfile
    container_name: quizzy-frontend
    ports:
      - "3001:3000"
    volumes:
      - .:/app                        
    depends_on:
      - backend

volumes:
  postgres-data:
